### ISSUE TITLE
Start server.py

### ISSUE THREAD

**Issue by darzunec1** [AILab-FOI/akdb#141]
xxx@xxx-Lenovo-G580:~/akdb-master/akdb/src/srv$ python server.py 
Traceback (most recent call last):
  File "server.py", line 12, in <module>
    import kalashnikovDB as ak47
  File "../swig/kalashnikovDB.py", line 28, in <module>
    _kalashnikovDB = swig_import_helper()
  File "../swig/kalashnikovDB.py", line 24, in swig_import_helper
    _mod = imp.load_module('_kalashnikovDB', fp, pathname, description)
ImportError: ../swig/_kalashnikovDB.so: undefined symbol: TEST_result

**Comment by TheWildHorse** [comment]
https://github.com/mschatten/akdb/pull/142
