### ISSUE TITLE
SWIG testovi

### ISSUE THREAD

**Issue by mschatten** [AILab-FOI/akdb#173]
Provjeriti koji testovi u mapi swig ne rade (#102) te:
1) Ako test ne radi zbog nekog C koda u pozadini, javiti da se c kod treba popraviti
2) Ako test ne radi zbog pogreške u Python kodu, popraviti tako da ispravno radi.

Također, bolje dokumentirati funkcije korištene za implementaciju.

**Comment by ivanmilas1** [comment]
Javljam se za rješavanje.

**Comment by ivanmilas1** [comment]
1. _doctest: tablePropertiesTests_ - test radi ispravno✔️
2. _doctest: relAlgebraTests_ - test se izvršava sa 8 uspješnih i 3 neuspješna testiranja, testiranje vraća neispravnost prilikom pozivanja funkcije verify_table koja vraća vrijednost -1.  ✔️
3. _doctest: relAlgebraTests_ - test se izvršava sa 4 uspješnih i 10 neuspješna testiranja, testiranje vraća neispravnost prilikom pozivanja funkcije verify_table koja vraća vrijednost -1. ✔️
4. _auxi : AK_tarjan_Test_ - test se izvršava te vraća da test nije uspio, potrebno je pregledati datoteku auxiliary.c, linija 875 te provjeriti zašto test vraća neuspjeh. ⚠️
5. _auxi : AK_observable_test_ - test radi ispravno✔️
6. _auxi: AK_observable_pattern_ - test radi ispravno✔️
7. _dm: AK_allocationbit_test_ - test radi ispravno✔️
8. _dm: AK_allocationtable_test_ - test radi ispravno✔️
9. _dm: AK_thread_safe_block_access_test_ - test započinje te odmah po početku zamrzne terminal i prekida sa izvršavanjem, potrebno je napraviti clean nakon pokretanja ovoga testa. Pogreška se javlja u datoteci dbman.c na liniji 2674 prilikom izvođenja for petlje. ❌
10. _file: AK_id_test_ - test radi ispravno✔️
11. _file: AK_files_test_ - test se izvrši i javlja da je test uspješno odrađen no nakon toga se javlja SIGSEGV pogreška. Treba pregledati funkciju AK_printout_redolog koja se nalazi u datoteci redo_log.c. ❌
12. _file: AK_fileio_test_ - test radi ispravno.✔️
13. _file: AK_op_rename_test_ - test radi ispravno no u jednom od n izvođenja dogodi se SIGSEGV pogreška. Trebalo bi pregledati funkciju AK_rename koja se nalazi u datoteci table.c ⚠️
14. _file: AK_filesort_test_ - test radi ispravno✔️
15. _file: AK_filesearch_test_ - test radi ispravno✔️
16. _file: AK_sequence_test_ - test radi ispravno✔️
17. _file: AK_table_test_ - test vraća SIGSEGV pogrešku, greška se nalazi unutar funkcije AK_table_test koja se nalazi u datoteci table.c. Greška se pojavljuje nakon linije 1140.❌
18. _idx: AK_bitmap_test_ - test vraća SIGSEGV pogrešku, greška se nalazi unutar funkcije AK_bitmap_test koja se nalazi u datoteci bitmap.c. Greška se pojavljuje na liniji 745 prilikom pozivanja funkcije AK_Insert_New_Element. Potrebno je napraviti clean nakon pokretanja ovoga testa.❌
19. _idx: AK_btree_test_ - test uzrokuje terminal da zablokira te se ništa ne izvršava, potrebno je napraviti clean nakon pokretanja ovog testa. Potencijalna greška se nalazi prilikom pozivanja funkcije AK_InsertAtEnd_L3 unutar funkcije AK_btree_test u datoteci btree.c.❌
20. _idx: AK_hash_test_ - nakon pokretanja testa javlja se SIGSEGV pogreška. Ova greška se događa nakon pokretanja petlje na 624 liniji koda u datoteci hash.c❌
21. _mm: AK_memoman_test_ - test radi ispravno✔️
22. _mm: AK_block_test2_ - test radi ispravno✔️
23. _opti: AK_rel_eq_assoc_test_ - test radi ali ne vraća da se ispravno izvršio. Trebalo bi provjeriti testne podatke i provjeriti dali su rezultati ispravni. Test se nalazi u datoteci rel_eq_assoc_test.c⚠️
24. _opti: AK_rel_eq_comut_test_- test radi ali ne vraća da se ispravno izvršio. Trebalo bi provjeriti testne podatke i provjeriti dali su rezultati ispravni. Test se nalazi u datoteci rel_eq_comut.c⚠️
25. _opti: AK_rel_eq_selection_test_- test radi ali ne vraća da se ispravno izvršio. Trebalo bi provjeriti testne podatke i provjeriti dali su rezultati ispravni. Test se nalazi u datoteci rel_eq_selection.c⚠️
26. _opti: AK_rel_eq_projection_test_- test radi ali ne vraća da se ispravno izvršio. Trebalo bi provjeriti testne podatke i provjeriti dali su rezultati ispravni. Test se nalazi u datoteci rel_eq_projection.c⚠️
27. _opti: AK_query_optimization_test_- test radi ispravno✔️
28. _rel: AK_op_union_test_ - test se ispravno izvodi no nekada se dogodi SIGSEGV pogreška. Prilikom pozivanja funkcije AK_get_segment_adresses_internal koja se nalazi u datoteci memoman.c. ❌
29. _rel: AK_op_join_test_ - test se ne izvodi jer ne postoji tablica nat_join_test. Trebalo bi implementirati tablicu da provjerimo ispravnost test. ❌
30. _ rel: AK_op_product_test_ - test se izvodi ispravno✔️
31. _rel: AK_aggregation_test_ -  test je prošao, no postoji problem jer tablica agg ne postoji stoga treba implementirati tu tablicu da vidimo dali se test ispravno izvodi. ❌
32. _rel: AK_op_intersect_test_ - test radi ispravno.✔️
33. _rel: AK_op_selection_test_ - test se izvodi do kraja no testiranja ne prolaze. Treba popraviti kod u datoteci selection.h ⚠️
34. _rel: AK_op_selection_test_pattern_ - - test se izvodi do kraja no testiranja ne prolaze. Treba popraviti kod u datoteci selection.h ⚠️
35. _ rel: AK_op_selection_test_redolog_ - test radi ispravno.✔️
36. _rel: AK_expressio_check_test_ - test radi ispravno.✔️
37. _rel: AK_op_difference_test_ - test ne postoji, prilikom upisa broja 37 poziva se test pod brojem 38.❌
38. _rel: AK_op_projection_test_ -  test se ne izvodi pravilno. Javlja se SIGSEGV pogreška. Pogledati u datoteci projection.c zbog čega se javlja navedena pogreška.❌
39. _rel: AK_op_theta_join_test_ - test se izvršava ali ne vraća ispravne rezultate. Test javlja da tablice theta_join_test, theta_join_test2, theta_join_test3 te theta_join_test4 ne postoje.  ❌
40. _sql: AK_test_command_ - test se izvršava, no javlja da testiranje nije uspješno. Provjeriti u datoteci command.c zbog čega varijabla test_command nema vrijednost EXIT_SUCCESS. ❌
41. _sql: AK_test_command_ - test se izvršava, 10 od 13 testiranja javlja neuspjeh. ✔️
42. _sql: AK_view_test_ - test se ruši prilikom pozivanja funkcije za preimenovanje. Konkretno, prilikom poziva funkcije AK_view_test, konkretno na liniji 345 u datoteci view.c. ❌
43. _sql: AK_nnull_constraint_test_ - test radi ispravno.✔️
44. _sql: AK_trigger_test_ - test se ne izvršava ispravno. Test javlja free(): invalid next size(fast),  Aborted(core dumped). Provjeriti u datoteci trigger.c nakon linije 402 zbog čega dolazi do pogreške. ❌
45. _sql: AK_unique_test_ -test se uspješno izvrši te javlja da je se 2 od 8 testiranja neuspješno.✔️
46. _sql: AK_reference_test_ - tablica ref_test ne postoji stoga test nije moguće izvršiti, provjeriti dali postoji tablica, ukoliko ne postoji dodati ju. ❌
47. _sql: AK_constraint_between_test_ - test radi ispravno.✔️
48. _sql: AK_check_constraint_test_ - test radi ispravno.✔️
49. _sql: AK_constraints_names_test_ - test radi ispravno.✔️
50. _sql: AK_test_Transaction_ - test ne radi. Započinje sa izvođenjem ali onda se zamrzne terminal. Provjeriti u datoteci transaction.c zbog čega dolazi do ove pogreške. ❌
51. _sql: AK_recovery_test_ - test radi ispravno✔️

**Comment by mzinic96** [comment]
Javljam se za ažuriranje stanja.

**Comment by mzinic96** [comment]
**STANJE NA 27.05.2020. 15:33**
**------------------------------------------**

Za početak, kod kompajliranja SWIG sučelja s naredbom "**swig -python kalashnikovDB.i**" javlja se **11 warninga** (9 ih je Warning 454 i 2 su Warning 509).

Potrebno je izvršiti još jednu naredbu kako bi se uspješno izvršio korak kompajliranja, a to je "**python setup.py build_ext --inplace**". Ovdje dolazi do sljedećeg errora:

**cc1: some warnings being treated as errors**
**error: command 'x86_64-linux-gnu-gcc' failed with exit status 1**

Kod pokretanja naredbe "**python allTests.py**" kako bi se pokrenuli svi testovi, dolazi do sljedećeg errora: "**NameError: name 'AK_op_selection_test_redolog' is not defined**". Potrebno je ili implementirati navedeni test ili ga je za početak dovoljno samo zakomentirati kako bi se moglo nastaviti dalje s testiranjem.

- Test 1: prolaze svi testovi :heavy_check_mark: 
- Test 2: jedan test od njih 11 ne prolazi (verify_table("student", ts.st_2, "table_test.txt") Expected: 0; Got: -1) :exclamation: 
- Test 3: dva testa od njih 14 ne prolaze (verify_table("product", ts.ra_1, "table_test.txt") i verify_table("union", ts.ra_3, "table_test.txt")) :exclamation: 
- Test 4: TEST: 1 of 1 tests FAILED :x:
- Test 5: TEST: 1 of 1 tests successful :heavy_check_mark: 
- Test 6: TEST: 1 of 1 tests successful :heavy_check_mark:
- Test 7: TEST: 3 of 3 tests successful :heavy_check_mark:
- Test 8: TEST: 1 of 1 tests successful :heavy_check_mark:
- Test 9: TEST: 50 of 50 tests successful :heavy_check_mark: 
- Test 10: TEST: 2 of 2 tests successful :heavy_check_mark:
- Test 11: Real SIGSEGV occured. Problematična funkcija AK_update_row_from_block :x:

Nakon pokretanja testa 11 koji završava s errorom, ponekad više nije moguće ponovno pokrenuti naredbu "**python allTests.py**". Može se ili probati ponovno par puta pokrenuti **allTests.py**, ponekad prođe ili se može napraviti "**Make**" cijelog akdb-a nakon čega opet radi

- Test 12: TEST: 8 of 8 tests successful :heavy_check_mark: 
- Test 13: Test je jednom izbacio Floating point exception (core dumped) dok je drugi puta sve prošlo dobro. TEST: 1 of 1 tests successful :exclamation: 

U slučaju da Test 13 ne prođe, opet se više ne može pokrenuti program **allTests.py**. Problem se može riješiti isto kao i kod Testa 11. 

- Test 14: TEST: 1 of 1 tests successful :heavy_check_mark: 
- Test 15: TEST: 1 of 1 tests successful :heavy_check_mark: 
- Test 16: TEST: 2 of 8 tests FAILED. Error while getting current and next value of 'sequence1'. :x:
- Test 17: Real SIGSEGV occured. Problematična funkcija AK_table_test unutar datoteke table.c :x:
- Test 18: Printing non existing index table. Table assistanrandom_bmapIndex does not exist. :x:

Nakon Testa 18, opet se ne može pokrenuti **allTests.py**. Rješenje je isto kao i prije. 

To isto rješenje koristite i za sve buduće errore zbog kojih se zaustavlja izvođenje programa **allTests.py** i onemogućuje njegovo ponovno pokrenuti. 

- Test 19: Real SIGSEGV occured. Problematična funkcija AK_btree_insert. :x:
- Test 20: Real SIGSEGV occured. Problematična funkcija AK_hash_test. :x:
- Test 21: TEST: 513 of 513 tests successful :heavy_check_mark: 
- Test 22: TEST: 257 of 257 tests successful :heavy_check_mark:
- Test 23: TEST: 4 of 4 tests successful :heavy_check_mark: 
- Test 24: TEST: 1 of 1 tests successful :heavy_check_mark: 
- Test 25: Real SIGSEGV occured. Problematična funkcija AK_update_row_from_block. :x:
- Test 26: Real SIGSEGV occured. Problematična funkcija AK_update_row_from_block. :x:
- Test 27: TEST: 1 of 1 tests successful :heavy_check_mark: 
- Test 28: free(): double free detected in tcache 2. Aborted (core dumped). Potrebno provjeriti AK_get_segment_adresses_internal u datoteci memoman.c. :x:
- Test 29: Table nat_join_test does not exist! AK_new_extent: ERROR. Problem with blocks allocation kalashnikov.db. Treba napraviti tablicu nat_join_test :x:
- Test 30: TEST: 1 of 1 tests successful :heavy_check_mark:
- Test 31: TEST PASSED! TEST: 32509 of 552320845 tests FAILED :exclamation: 
- Test 32: TEST: 1 of 1 tests successful :heavy_check_mark: 
- Test 33: TEST: 2 of 2 tests FAILED. AK_new_extent: ERROR. Problem with blocks allocation kalashnikov.db. :x:
- Test 34: TEST: 4 of 4 tests FAILED. AK_new_extent: ERROR. Problem with blocks allocation kalashnikov.db. :x:
- Test 35: TEST: 5 of 5 tests successful :heavy_check_mark: 
- Test 36: TEST: 1 of 1 tests successful. :heavy_check_mark: 
- Test 37: TEST: 2 of 2 tests successful. :heavy_check_mark: 
- Test 38: Real SIGSEGV occured. Problematična funkcija AK_Insert_New_Element_For_Update :x:
- Test 39: TEST: 1 of 1 tests FAILED. AK_new_extent: ERROR. Problem with blocks allocation kalashnikov.db. :x:
- Test 40: TEST: 10 of 13 tests FAILED. Prvi, predzadnji i zadnji testovi uspješno se izvrše. :exclamation: 
- Test 41: free(): invalid pointer. Aborted (core dumped). Test 5 - Show view data ne prolazi. Provjeriti AK_sequence :x:
- Test 42: TEST: 4 of 4 tests successful. :heavy_check_mark: 
- Test 43: free(): invalid next size (fast). Aborted (core dumped). Provjeriti AK_trigger_conditions. :x:
- Test 44: Real SIGSEGV occured. Provjeriti funkciju AK_tuple_to_string. :x:
- Test 45: TEST: 1 of 1 tests FAILED. Table ref_test does not exist! Potrebno je napraviti tablicu ref_test. :x:
- Test 46: TEST: 3 of 3 tests successful :heavy_check_mark: 
- Test 47: TEST: 6 of 12 tests FAILED. Test 6 error: Failed to add 'check constraint' on TABLE: student. :x:
- Test 48: TEST: 1 of 1 tests successful :heavy_check_mark: 
- Test 49: TEST: Test is still not reporting the results correctly. Read https://github.com/mschatten/akdb/wiki/Reporting-Test-Results. Provjeriti datoteku transaction.c :exclamation:
- Test 50: Uspješni recovery insert. TEST: 1 of 1 tests successful :heavy_check_mark: 
- Test 51: IndexError: list index out of range. Na popisu piše da postoji i 51. test, ali očito da ga nema. :x:

**Za kraj treba naglasiti** da nakon što se dogode određene greške, rezultati testova znaju varirati, odnosno prije nego što se pojavi neka greška test daje jedan rezultat dok nakon što se pojavi greška taj isti test daje neki drugi rezultat. **Npr.** dok se test 1 prvi puta pokrene, sve prođe dobro (uspješno se izvrši), ali nakon što se pojavi neka teža greška (error) u nekom drugom testu i ponovno se proba pokrenuti test 1, on više ne prolazi (izbaci **Real SIGSEGV occured** error).

**Comment by igalovic** [comment]
Javljam se za ažuriranje stanja.

**Comment by igalovic** [comment]
**STANJE NA 04.05.2021. 15:50
------------------------------------------**

Za početak, sve upute koje je kolega Matija Žinić(kchunter) naveo na početku vrijede i danas. Test AK_op_selection_test_redolog ostao je ne implementiran i dan danas pa ga kod pokretanja swig testova naredbom python allTests.py treba zakomentirati ili implementirati.


doctest: tablePropertiesTests : prolaze svi testovi :heavy_check_mark:
doctest selectionTEsts: jedan test od njih 11 ne prolazi : File "selectionTests.py", line 47, in
selectionTests.selection_test Failed example: f.verify_table("student",ts.st_2,"table_test.txt") :x: 
Expected:0
Got:-1, 

doctest:relAlgebraTests: 2 testa od njih 14 ne prolaze :x: 
Failed example:
    f.verify_table("union", ts.ra_3, "table_test.txt")
Expected:
    0
Got:
    -1

Failed example:
    f.verify_table("product", ts.ra_1, "table_test.txt")
Expected:
    0
Got:
    -1
    
    
auxi:AK:tarjan_test: TEST: 1 of 1 tests FAILED :x: 
auxi_AK_observable_test: TEST: 1 of 1 tests successful.:heavy_check_mark:
auxi_AK_observable_pattern: TEST: 1 of 1 tests successful.:heavy_check_mark:
dm:AK_allocationonbit_test: TEST: 3 of 3 tests successful.:heavy_check_mark:
dm:AK_allocationtable_test: TEST: 1 of 1 tests successful.:heavy_check_mark:
dm_AK_thread_safe_block_access_test: TEST: 50 of 50 tests successful.:heavy_check_mark:
file:AK_id_test: TEST: 2 of 2 tests successful.:heavy_check_mark:
file:AK_files_test: Real SIGSEGV occured *************
python: ../auxi/mempro.c:134: AK_debmod_signal_callback: Assertion `mprotect_sigsegv' failed.
Aborted (core dumped)
test se izvrši i javlja da je test uspješno odrađen(AK_init_new_segment: Test1 succeded!) no nakon toga se javlja SIGSEGV pogreška. Treba pregledati funkciju AK_printout_redolog koja se nalazi u datoteci redo_log.c. :x: 

file:AK_fileio_test: TEST: 8 of 8 tests successful. :heavy_check_mark:
file:AK_op_rename_test: Prvi puta vraća TEST: 1 of 1 tests successful , u prvom ili bilo kojem drugom pokušaju testiranja može vratiti :Floating point exception (core dumped), a nakon toga je test uvijek uspješan. Treba pogledati funkciju ak_rename koja se nalazi u datoteci table.c. :warning: 
file:AK_filesort_test: TEST: 1 of 1 tests successful. :heavy_check_mark:
file:AK_filesearch_test: TEST: 1 of 1 tests successful. :heavy_check_mark:
file:AK_sequence_test: Error while getting current value of 'sequence1'(TEST: 2 of 8 tests FAILED). Problem je u funkciji AK_sequence_get_id u datoteci sequence.c koja dohavati krivi id. Ako se promjene vrijednosti koje se treba provjeriti na 119 i 124 test radi uspješno(TEST: 8 of 8 tests successful.). Neovisno o tome kako se test pokrene kada pokušamo ponovno pokrenuti test, test javlja grešku invalid pointer.
Error while getting next value 'sequence1'. :x: 




file:AK_table_test: Tablica student postoji, ali se ne može dohvatiti index vrijednosti 3 u tablici student.
test vraća SIGSEGV pogrešku, greška se nalazi unutar funkcije AK_table_test koja se nalazi u datoteci table.c. Greška se pojavljuje nakon linije 1140. :x: 

idx:AK_bitmap_test: test vraća SIGSEGV pogrešku, greška se nalazi unutar funkcije AK_Insert_New_Element_For_Update koja se nalazi u datoteci fileio.c i ne može se napraviti AK_debmod_signal_callback funkcija zbog toga . Potrebno je napraviti make clean nakon pokretanja ovoga testa. :x: 

idx_AK_btree_test:Test također vraća sigsegv pogrešku. Funkcija AK_btree_insert je problem koja se nalazi u datoteci btree.c. Nakon pogreške ne može se dobiti AK_debmod_signal_callback i javlja se greška assertion 'mprotect_sigsegv' failed. :x: 

idx: AK_hash_test - nakon pokretanja testa javlja se SIGSEGV pogreška. Ova greška se događa unutar funkcije AK_hash_test() nakon pokretanja petlje  na 627 liniji koda u datoteci hash.c :x: 

mm:AK_memoman_test: TEST: 513 of 513 tests successful. :heavy_check_mark:
mm:AK_block_test2: TEST: 257 of 257 tests successful. :heavy_check_mark:
opti:AK_rel_eq_assoc_test: TEST: 4 of 4 tests successful. Nakon nekoliko neuspješnih testova(npr. 18,19,20) vraća TEST: 2 of 4 tests FAILED.  :warning: 
opti:AK_rel_eq_comut_test: TEST: 1 of 1 tests successful. Nakon nekoliko neuspješnih testova test ne radi(TEST: 1 of 1 tests FAILED) ili ako tri puta zaredom pokrenemo test nakon što smo napravili make clean programa vraća sigsegv pogrešku(greška se tada javlja u AK_update_row_from_block funkciji koja se nalazi u datoteci fileio.c ). Ponovnim pokretanjem naredbe python allTests.py test prvi puta radi , a drugi puta ponovno vraća sigsegv pogrešku. :warning: 
opti:AK_rel_qe_selection_test: TEST: 2 of 2 tests successful. Nakon drugog pokretanja testa ponovno se javlja sigsev pogreška i greška je ista kao i u prethodnom testu. Ponovnim pokretanjem naredbe python allTests.py test prvi puta radi , a drugi puta ponovno vraća sigsegv pogrešku. :warning: 
opti:AK_rel_eq_projection_test : TEST: 1 of 1 tests successful. :heavy_check_mark:
opti:AK_query_optimization_test: TEST: 1 of 1 tests successful.:heavy_check_mark:
rel:AK_op_union_test: free(): double free detected in tcache 2. Aborted (core dumped). Potrebno provjeriti AK_get_segment_adresses_internal funkciju u datoteci memoman.c . Nakon što se napravi make clean projekta prvi puta ponovno izbacuje istu pogrešku ,a svaki sljedeći put kada se pokrene naredba python allTests.py vraća TEST 1 of 1 tests successful  :warning:  
rel:AK_op_join_test: TEST: 1 of 1 tests FAILED. Tablica nat_join_test ne postoji pa niti test ne radi. :x: 
rel:AK_op_product_test: TEST: 1 of 1 tests successful. :heavy_check_mark:
rel:AK_op_aggregation_test: Javlja da je tablica _agg kreirana i nakon da napravio novi segment i nakon toga .Floating point exception (core dumped) Test ne prolazi.  //TEST PASSED! TEST: 0 of 0 tests successful. Svaki sljedeći puta se ponovno javlja floating point exception i da tablica agg već postoji. :x: 
rel:AK_op_intersect: Prvi puta zna javiti da ne postoji table intersect_test i izbacuje core dumped, a svaki sljedeći test javlja Test succeeded! TEST: 1 of 1 tests successful. :warning: 
rel:AK_op_selection_test: Prvi puta nakon što se napravi make clean projekta se uspješno izvede test, dok se u ostalim slučajevima javlja da je test pao .TEST: 2 of 2 tests FAILED. :x: 
rel: AK_op_selection_test_pattern : Prvi puta All tests finished successfully. :) TEST: 4 of 4 tests successful. , a za svaki ostali put TEST: 4 of 4 tests FAILED. Nekada i greška core dumped  :x: 
rel: AK_op_selection_test_redolog: TEST: 5 of 5 tests successful.:heavy_check_mark:
rel: AK_expression_check_test: 1 of 1 tests successful.:heavy_check_mark:
rel: AK_op_difference_test: 4 of 4 tests successful. :heavy_check_mark:
rel: AK_op_projection_test: munmap_chunk() : invalid pointer je greška koja se javlja. Aborted(core dumped) , a svaki sljedeći puta se javlja sljedeća greška free(): invalid next size (fast) :x: 
rel: AK_op_theta_join_test: TEST: 1 of 1 tests successful. Nakon nekoliko neuspješnih testova(npr. koji vraćaju core dumped ili sigsegv) vraća TEST: 1 of 1 tests FAILED. :warning: 
sql: AK_test_command : Prvi put nakon make clean projekta 9 of 13 tests FAILED, idući puta TEST: 10 of 13 tests FAILED i svaki sljedeći put kada se pokrene test je 11 of 13 tests FAILED. :x: 
sql: AK_drop_test : TEST: 6 of 6 tests successful. :heavy_check_mark:
sql: AK_view_test: Prvi puta nakon što se napravi make clean projekta TEST: 4 of 4 tests successful. Drugi i svaki sljedeći put: 1 of 3 tests failed. FAILURE! Constraint name is not unique jer on već postoji u bazi podataka. :warning: 
sql: AK_null_constraint_test: free(): invalid next size (fast) Aborted (core dumped). Provjeriti AK_trigger_conditions tablicu. :x:
sql: AK_trigger_test: TEST: 2 of 8 tests FAILED. Drugi puta i svaki sljedeći put kada se pokrene 7 of 8 tests FAILED iz razloga što već postoje neki od constraintova.
Npr.
FAILURE!
UNIQUE constraint already exists on (combination of) attribute(s): mbr[{(|&&|)}]lastname[{(|&&|)}]weight
of table: student
FAILURE!
Existing values in table: student
would violate UNIQUE constraint which You would like to set on (combination of) attribute(s): firstname
:x: 

sql: AK_unique_test: TEST: 1 of 1 tests FAILED. Tablica ref_test je prazna. :x: 
sql: AK_reference_test: TEST: 3 of 3 tests successful . 3.put nakon izvođenja testa se dogodi sljedeće: *** stack smashing detected ***: terminated Aborted (core dumped). Grešla u funkciji AK_read_constraint_between koja se nalazi u datoteci between.c. :warning:  
sql: AK_constraint_between_test : *** TEST 7 Successful! *** TEST: 13 of 13 tests successful. :heavy_check_mark:
sql: AK_check_constraint_test: TEst succeeded. TEST: 1 of 1 tests successful. :heavy_check_mark:

sql: AK_constraint_names_test: test ne prikazuje nikakve rezultate. Test ponekad završava u deadlocku AK_new_extent: ERROR. Problem with blocks allocation kalashnikov.db, a češće javlja da test još uvije ne piše izvještaj o testovima. TEST: Test is still not reporting the results correctly. Read https://github.com/mschatten/akdb/wiki/Reporting-Test-Results. Provjeriti datoteku transaction.c :x: 

trans: AK_test_Transaction : Uspješni revocery insert - TEST: 1 of 1 tests successful- :heavy_check_mark:

rec: AK_recovery_test: Test: 51
Traceback (most recent call last):
  File "allTests.py", line 216, in <module>
    res=listTests[x]()
IndexError: list index out of range . Na popisu postoji index, ali ga očito nema prilikom testiranja. :x:
